complexity:
  LongParameterList:
    allowedFunctionParameters: 8
    ignoreDefaultParameters: true
  TooManyFunctions:
    ignoreAnnotatedFunctions: ['Preview']

naming:
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*'

style:
  UnusedPrivateFunction:
    ignoreAnnotated: [ 'Preview' ]
