complexity:
  LongMethod:
    active: true
    ignoreAnnotated: [ 'Composable' ]
  LongParameterList:
    allowedFunctionParameters: 8
    ignoreDefaultParameters: true
  TooManyFunctions:
    ignoreAnnotatedFunctions: [ 'Preview' ]

naming:
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]
  FunctionNameMaxLength:
    excludes: [ '**/test/**', '**/*Test.kt', '**/*Spec.kt' ]
    ignoreAnnotated: ['Preview']
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*|[A-Z][_A-Z0-9]*'

style:
  MaxLineLength:
    active: false
  UnusedPrivateFunction:
    ignoreAnnotated: [ 'Preview' ]
  CascadingCallWrapping:
    active: false

comments:
  UndocumentedPublicProperty:
    active: false
  UndocumentedPublicFunction:
    active: false
  UndocumentedPublicClass:
    active: false

empty-blocks:
  EmptyFunctionBlock:
    active: false # actual functions
